### ISSUE TITLE
Text not centered

### ISSUE THREAD

**Issue by chrise86** [bjedrocha/avatar_magick#1]
The initials are appearing off center - closer to the top:

![avatar](https://cloud.githubusercontent.com/assets/616956/11298908/42e91d16-8f7a-11e5-90e2-6064724d4905.png)

Any ideas? Not adjusting any options other than background colour.

dragonfly (1.0.10)
rails (4.2.4)

**Comment by bjedrocha** [comment]
I haven't noticed this. Can you try using a different font using the `font` option? The library defaults to 'Arial Regular`.

E.g.
```ruby
Dragonfly.app.generate(:initial_avatar, "Oliver Murphy", {background_color: 'b71c1c', font: 'Georgia'})
```

**Comment by bradpurchase** [comment]
Definitely seeing the text displaying not quite vertically centered here as well with default settings - example: https://www.dropbox.com/s/oyqijpmr26pr3c7/avatar.png?dl=0

**Comment by bjedrocha** [comment]
@bradpurchase can you tell me which version of ImageMagick is installed on your system?

```
convert -version
```

I was able to reproduce this morning while running version 6.9.4-3. I've updated my version to 6.9.5-4 and the text is once again centered. Thanks.

**Comment by bjedrocha** [comment]
I pushed a [new version](https://rubygems.org/gems/avatar_magick/versions/1.0.2) of the gem that addresses the above issue. Please update the reference in your Gemfile.

Thanks for bringing this to my attention. Cheers.

**Comment by bradpurchase** [comment]
Awesome, thanks @bjedrocha! 👍
