### ISSUE TITLE
Causes undefined method error for avatar_size

### ISSUE THREAD

**Issue by iamdriz** [bjedrocha/avatar_magick#3]
When following the tutorial on: http://markevans.github.io/dragonfly/rails to allow a user to upload a photo for a model, I get this error: `undefined method 'avatar_size=' for #<User:0x007fe56740aac0>`.
Happens when trying to update the attributes:
~~~
def update
    @user = User.find(params[:id])
    if @user.update_attributes(update_user_params)
      redirect_to users_path
    else
      render 'edit'
...
~~~
The params are:
~~~
def update_user_params
  params.require(:user).permit(:avatar)
end
~~~
Disabling the concern fixes the issue... Any ideas why?

**Comment by bjedrocha** [comment]
Hey @iamdriz, have you taken a look at the [example project](https://github.com/bjedrocha/avatar-magick-example/tree/dragonfly-attachments)? It's a working Rails application that shows how to use Dragonfly for handling upload attachments and AvatarMagick for default avatars.

See if you can get the [dragonfly-attachments](https://github.com/bjedrocha/avatar-magick-example/tree/dragonfly-attachments) branch up and running and see where it differs from what you're trying to accomplish. If you run into any issues, let me know.

**Comment by iamdriz** [comment]
@bjedrocha Ah so I fixed it by renaming avatar to photo in the DB and models. Seems that if you have your columns named `avatar_uid` and `avatar_name` it conflicts with the concern!

**Comment by bjedrocha** [comment]
Ah right, good catch! I will make that configurable and add a note to the README. Thanks for the detective work and follow up. Glad you got it working 😄
